### ISSUE TITLE
Spelling mitsake

### ISSUE THREAD

**Issue by zaidedan** [bgranzow/pe#1]
app.cc spells "solving" as "sovling" . Lern to spel corectly

https://github.com/bgranzow/pe/blob/master/app.cc#L16

**Comment by bgranzow** [comment]
i fixd ths

**Comment by zaidedan** [comment]
lpl

On Wed, Jul 15, 2015 at 10:16 PM, Brian Granzow notifications@github.com
wrote:

> i fixd ths
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bgranzow/pe/issues/1#issuecomment-121802431.

## 

Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com http://www.danielzaide.com
